name: Test
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - run: npm ci
      - uses: actions/upload-artifact@v2
        with:
          name: workspace-${{ github.run_id }}
          path: ${{ github.workspace }}
          retention-days: 1
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - uses: actions/download-artifact@v2
        with:
          name: workspace-${{ github.run_id }}
      - run: npm test -- --ci
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - uses: actions/download-artifact@v2
        with:
          name: workspace-${{ github.run_id }}
      - run: npm run lint
